const MAX_PLAYLIST_NAME_LENGTH = 100;
const SEPARATOR = " — ";

/**
 * Build a playlist title from a prefix and label, with optional part number.
 * Handles collision suffix, sanitization, and length capping.
 */
export function buildPlaylistTitle(
  prefix: string,
  label: string,
  partNumber?: number,
): string {
  const sanitizedPrefix = sanitize(prefix);
  const sanitizedLabel = sanitize(label);

  let title = sanitizedPrefix
    ? `${sanitizedPrefix}${SEPARATOR}${sanitizedLabel}`
    : sanitizedLabel;

  if (partNumber !== undefined) {
    title = `${title}${SEPARATOR}Part ${String(partNumber).padStart(2, "0")}`;
  }

  return capLength(title);
}

/**
 * Build a playlist description mentioning strategy, track count, and timestamp.
 */
export function buildPlaylistDescription(
  strategy: string,
  trackCount: number,
  groupLabel: string,
): string {
  const timestamp = new Date().toISOString().split("T")[0];
  return `${trackCount} tracks • Grouped by ${strategy}: ${groupLabel} • Generated by SpotiPlay on ${timestamp}`;
}

/**
 * Resolve naming collisions by appending a numeric suffix.
 * Returns a new title that is not in the existingTitles set.
 */
export function resolveCollision(title: string, existingTitles: Set<string>): string {
  if (!existingTitles.has(title)) return title;

  let i = 2;
  while (true) {
    const candidate = capLength(`${title} (${i})`);
    if (!existingTitles.has(candidate)) return candidate;
    i++;
  }
}

function sanitize(str: string): string {
  return str
    .trim()
    .replace(/\s+/g, " ") // collapse multiple spaces
    .replace(/[^\w\s\-–—&'",.:;!?()/#+]/g, "") // strip unusual chars (keep # for alpha buckets)
    .trim();
}

function capLength(str: string): string {
  if (str.length <= MAX_PLAYLIST_NAME_LENGTH) return str;
  return str.slice(0, MAX_PLAYLIST_NAME_LENGTH - 1).trimEnd() + "…";
}

/**
 * Get the first letter bucket for alphabetical grouping.
 * Non-letter characters go to "#".
 */
export function getAlphaBucket(str: string): string {
  const cleaned = str.trim().replace(/^(the |a |an )/i, ""); // strip common articles
  const first = cleaned[0]?.toUpperCase() ?? "#";
  return /^[A-Z]$/.test(first) ? first : "#";
}

/**
 * Get a decade label like "1990s" from a year.
 */
export function getDecadeLabel(year: number): string {
  const decade = Math.floor(year / 10) * 10;
  return `${decade}s`;
}
