import type { CanonicalGenre } from "./taxonomy";

/**
 * Deterministic mapping from normalized Spotify genre strings → canonical genre + confidence weight.
 * Weight represents how strongly this raw tag implies the canonical genre (0–1).
 */
export interface CanonicalEntry {
  genre: CanonicalGenre;
  weight: number;
}

export const CANONICAL_MAP: Record<string, CanonicalEntry> = {
  // ── Pop ──────────────────────────────────────────────────────────────────
  "pop": { genre: "Pop", weight: 0.9 },
  "dance pop": { genre: "Pop", weight: 0.95 },
  "electropop": { genre: "Pop", weight: 0.85 },
  "synth-pop": { genre: "Pop", weight: 0.85 },
  "synthpop": { genre: "Pop", weight: 0.85 },
  "teen pop": { genre: "Pop", weight: 0.95 },
  "pop rock": { genre: "Pop", weight: 0.8 },
  "power pop": { genre: "Pop", weight: 0.85 },
  "chamber pop": { genre: "Pop", weight: 0.75 },
  "dream pop": { genre: "Pop", weight: 0.7 },
  "bubblegum pop": { genre: "Pop", weight: 0.95 },
  "adult contemporary": { genre: "Pop", weight: 0.85 },
  "europop": { genre: "Pop", weight: 0.9 },
  "boy band": { genre: "Pop", weight: 0.95 },
  "girl group": { genre: "Pop", weight: 0.95 },
  "neo soul pop": { genre: "Pop", weight: 0.7 },
  "viral pop": { genre: "Pop", weight: 0.9 },
  "bedroom pop": { genre: "Indie/Alternative", weight: 0.75 },
  "art pop": { genre: "Indie/Alternative", weight: 0.7 },
  "hyperpop": { genre: "Electronic/Dance", weight: 0.75 },

  // ── Hip-Hop / Rap ─────────────────────────────────────────────────────────
  "hip hop": { genre: "Hip-Hop/Rap", weight: 0.95 },
  "hip-hop": { genre: "Hip-Hop/Rap", weight: 0.95 },
  "rap": { genre: "Hip-Hop/Rap", weight: 0.95 },
  "trap": { genre: "Hip-Hop/Rap", weight: 0.9 },
  "drill": { genre: "Hip-Hop/Rap", weight: 0.9 },
  "uk drill": { genre: "Hip-Hop/Rap", weight: 0.9 },
  "chicago drill": { genre: "Hip-Hop/Rap", weight: 0.9 },
  "gangsta rap": { genre: "Hip-Hop/Rap", weight: 0.95 },
  "conscious hip hop": { genre: "Hip-Hop/Rap", weight: 0.95 },
  "southern hip hop": { genre: "Hip-Hop/Rap", weight: 0.95 },
  "east coast hip hop": { genre: "Hip-Hop/Rap", weight: 0.95 },
  "west coast hip hop": { genre: "Hip-Hop/Rap", weight: 0.95 },
  "alternative hip hop": { genre: "Hip-Hop/Rap", weight: 0.9 },
  "indie hip hop": { genre: "Hip-Hop/Rap", weight: 0.85 },
  "boom bap": { genre: "Hip-Hop/Rap", weight: 0.95 },
  "lo-fi hip hop": { genre: "Ambient/Lo-fi", weight: 0.8 },
  "lofi hip hop": { genre: "Ambient/Lo-fi", weight: 0.8 },
  "phonk": { genre: "Hip-Hop/Rap", weight: 0.85 },
  "cloud rap": { genre: "Hip-Hop/Rap", weight: 0.85 },
  "mumble rap": { genre: "Hip-Hop/Rap", weight: 0.9 },
  "crunk": { genre: "Hip-Hop/Rap", weight: 0.9 },
  "uk hip hop": { genre: "Hip-Hop/Rap", weight: 0.95 },
  "trap soul": { genre: "R&B/Soul", weight: 0.75 },
  "rage rap": { genre: "Hip-Hop/Rap", weight: 0.9 },

  // ── Rock ──────────────────────────────────────────────────────────────────
  "rock": { genre: "Rock", weight: 0.9 },
  "classic rock": { genre: "Rock", weight: 0.95 },
  "hard rock": { genre: "Rock", weight: 0.95 },
  "soft rock": { genre: "Rock", weight: 0.85 },
  "arena rock": { genre: "Rock", weight: 0.95 },
  "glam rock": { genre: "Rock", weight: 0.9 },
  "psychedelic rock": { genre: "Rock", weight: 0.85 },
  "progressive rock": { genre: "Rock", weight: 0.85 },
  "prog rock": { genre: "Rock", weight: 0.85 },
  "garage rock": { genre: "Rock", weight: 0.85 },
  "blues rock": { genre: "Rock", weight: 0.85 },
  "southern rock": { genre: "Rock", weight: 0.9 },
  "desert rock": { genre: "Rock", weight: 0.85 },
  "stoner rock": { genre: "Rock", weight: 0.85 },
  "grunge": { genre: "Rock", weight: 0.9 },
  "post-grunge": { genre: "Rock", weight: 0.85 },
  "alternative rock": { genre: "Indie/Alternative", weight: 0.8 },
  "indie rock": { genre: "Indie/Alternative", weight: 0.9 },
  "folk rock": { genre: "Folk/Acoustic", weight: 0.75 },

  // ── Indie / Alternative ───────────────────────────────────────────────────
  "indie": { genre: "Indie/Alternative", weight: 0.9 },
  "alternative": { genre: "Indie/Alternative", weight: 0.85 },
  "indie pop": { genre: "Indie/Alternative", weight: 0.9 },
  "indie folk": { genre: "Indie/Alternative", weight: 0.8 },
  "shoegaze": { genre: "Indie/Alternative", weight: 0.9 },
  "post-punk": { genre: "Indie/Alternative", weight: 0.85 },
  "post-punk revival": { genre: "Indie/Alternative", weight: 0.9 },
  "emo": { genre: "Indie/Alternative", weight: 0.85 },
  "midwest emo": { genre: "Indie/Alternative", weight: 0.9 },
  "math rock": { genre: "Indie/Alternative", weight: 0.85 },
  "lo-fi indie": { genre: "Indie/Alternative", weight: 0.8 },
  "chillwave": { genre: "Indie/Alternative", weight: 0.8 },
  "twee pop": { genre: "Indie/Alternative", weight: 0.9 },
  "noise pop": { genre: "Indie/Alternative", weight: 0.85 },
  "sadcore": { genre: "Indie/Alternative", weight: 0.85 },
  "slacker rock": { genre: "Indie/Alternative", weight: 0.85 },
  "new wave": { genre: "Indie/Alternative", weight: 0.75 },

  // ── R&B / Soul ────────────────────────────────────────────────────────────
  "r&b": { genre: "R&B/Soul", weight: 0.95 },
  "soul": { genre: "R&B/Soul", weight: 0.95 },
  "neo soul": { genre: "R&B/Soul", weight: 0.95 },
  "contemporary r&b": { genre: "R&B/Soul", weight: 0.95 },
  "funk": { genre: "R&B/Soul", weight: 0.85 },
  "motown": { genre: "R&B/Soul", weight: 0.95 },
  "quiet storm": { genre: "R&B/Soul", weight: 0.9 },
  "urban contemporary": { genre: "R&B/Soul", weight: 0.85 },
  "gospel": { genre: "R&B/Soul", weight: 0.8 },
  "afropop": { genre: "World/Regional", weight: 0.75 },
  "alternative r&b": { genre: "R&B/Soul", weight: 0.9 },
  "new jack swing": { genre: "R&B/Soul", weight: 0.95 },

  // ── Electronic / Dance ────────────────────────────────────────────────────
  "electronic": { genre: "Electronic/Dance", weight: 0.9 },
  "edm": { genre: "Electronic/Dance", weight: 0.95 },
  "house": { genre: "Electronic/Dance", weight: 0.95 },
  "deep house": { genre: "Electronic/Dance", weight: 0.95 },
  "tech house": { genre: "Electronic/Dance", weight: 0.95 },
  "progressive house": { genre: "Electronic/Dance", weight: 0.95 },
  "electro house": { genre: "Electronic/Dance", weight: 0.95 },
  "future house": { genre: "Electronic/Dance", weight: 0.95 },
  "tropical house": { genre: "Electronic/Dance", weight: 0.9 },
  "techno": { genre: "Electronic/Dance", weight: 0.95 },
  "trance": { genre: "Electronic/Dance", weight: 0.95 },
  "drum and bass": { genre: "Electronic/Dance", weight: 0.95 },
  "drum & bass": { genre: "Electronic/Dance", weight: 0.95 },
  "dnb": { genre: "Electronic/Dance", weight: 0.95 },
  "dubstep": { genre: "Electronic/Dance", weight: 0.95 },
  "future bass": { genre: "Electronic/Dance", weight: 0.9 },
  "bass music": { genre: "Electronic/Dance", weight: 0.9 },
  "electro": { genre: "Electronic/Dance", weight: 0.85 },
  "disco": { genre: "Electronic/Dance", weight: 0.8 },
  "nu-disco": { genre: "Electronic/Dance", weight: 0.85 },
  "dance": { genre: "Electronic/Dance", weight: 0.85 },
  "uk garage": { genre: "Electronic/Dance", weight: 0.9 },
  "breakbeat": { genre: "Electronic/Dance", weight: 0.9 },
  "glitch hop": { genre: "Electronic/Dance", weight: 0.9 },
  "idm": { genre: "Electronic/Dance", weight: 0.85 },
  "ambient house": { genre: "Electronic/Dance", weight: 0.75 },
  "jersey club": { genre: "Electronic/Dance", weight: 0.9 },
  "grime": { genre: "Electronic/Dance", weight: 0.8 },
  "jungle": { genre: "Electronic/Dance", weight: 0.9 },

  // ── Metal ─────────────────────────────────────────────────────────────────
  "metal": { genre: "Metal", weight: 0.95 },
  "heavy metal": { genre: "Metal", weight: 0.95 },
  "death metal": { genre: "Metal", weight: 0.95 },
  "black metal": { genre: "Metal", weight: 0.95 },
  "thrash metal": { genre: "Metal", weight: 0.95 },
  "speed metal": { genre: "Metal", weight: 0.95 },
  "power metal": { genre: "Metal", weight: 0.95 },
  "doom metal": { genre: "Metal", weight: 0.95 },
  "sludge metal": { genre: "Metal", weight: 0.95 },
  "groove metal": { genre: "Metal", weight: 0.95 },
  "metalcore": { genre: "Metal", weight: 0.9 },
  "deathcore": { genre: "Metal", weight: 0.95 },
  "mathcore": { genre: "Metal", weight: 0.9 },
  "nu metal": { genre: "Metal", weight: 0.9 },
  "nu-metal": { genre: "Metal", weight: 0.9 },
  "folk metal": { genre: "Metal", weight: 0.9 },
  "symphonic metal": { genre: "Metal", weight: 0.9 },
  "progressive metal": { genre: "Metal", weight: 0.9 },
  "alternative metal": { genre: "Metal", weight: 0.85 },

  // ── Punk / Hardcore ───────────────────────────────────────────────────────
  "punk": { genre: "Punk/Hardcore", weight: 0.95 },
  "punk rock": { genre: "Punk/Hardcore", weight: 0.95 },
  "hardcore": { genre: "Punk/Hardcore", weight: 0.9 },
  "hardcore punk": { genre: "Punk/Hardcore", weight: 0.95 },
  "pop punk": { genre: "Punk/Hardcore", weight: 0.9 },
  "skate punk": { genre: "Punk/Hardcore", weight: 0.95 },
  "melodic hardcore": { genre: "Punk/Hardcore", weight: 0.95 },
  "post-hardcore": { genre: "Punk/Hardcore", weight: 0.9 },
  "screamo": { genre: "Punk/Hardcore", weight: 0.9 },
  "anarcho-punk": { genre: "Punk/Hardcore", weight: 0.95 },
  "crust punk": { genre: "Punk/Hardcore", weight: 0.95 },
  "oi": { genre: "Punk/Hardcore", weight: 0.9 },

  // ── Jazz / Blues ──────────────────────────────────────────────────────────
  "jazz": { genre: "Jazz/Blues", weight: 0.95 },
  "blues": { genre: "Jazz/Blues", weight: 0.95 },
  "bebop": { genre: "Jazz/Blues", weight: 0.95 },
  "cool jazz": { genre: "Jazz/Blues", weight: 0.95 },
  "smooth jazz": { genre: "Jazz/Blues", weight: 0.95 },
  "acid jazz": { genre: "Jazz/Blues", weight: 0.9 },
  "nu jazz": { genre: "Jazz/Blues", weight: 0.9 },
  "jazz fusion": { genre: "Jazz/Blues", weight: 0.9 },
  "contemporary jazz": { genre: "Jazz/Blues", weight: 0.95 },
  "chicago blues": { genre: "Jazz/Blues", weight: 0.95 },
  "delta blues": { genre: "Jazz/Blues", weight: 0.95 },
  "electric blues": { genre: "Jazz/Blues", weight: 0.95 },
  "swamp blues": { genre: "Jazz/Blues", weight: 0.95 },
  "free jazz": { genre: "Jazz/Blues", weight: 0.9 },
  "big band": { genre: "Jazz/Blues", weight: 0.9 },
  "swing": { genre: "Jazz/Blues", weight: 0.85 },

  // ── Classical / Orchestral ────────────────────────────────────────────────
  "classical": { genre: "Classical/Orchestral", weight: 0.95 },
  "orchestral": { genre: "Classical/Orchestral", weight: 0.95 },
  "opera": { genre: "Classical/Orchestral", weight: 0.95 },
  "baroque": { genre: "Classical/Orchestral", weight: 0.95 },
  "romantic": { genre: "Classical/Orchestral", weight: 0.85 },
  "chamber music": { genre: "Classical/Orchestral", weight: 0.95 },
  "neoclassical": { genre: "Classical/Orchestral", weight: 0.85 },
  "contemporary classical": { genre: "Classical/Orchestral", weight: 0.95 },
  "minimalism": { genre: "Classical/Orchestral", weight: 0.8 },
  "avant-garde": { genre: "Classical/Orchestral", weight: 0.7 },

  // ── Country / Americana ───────────────────────────────────────────────────
  "country": { genre: "Country/Americana", weight: 0.95 },
  "americana": { genre: "Country/Americana", weight: 0.95 },
  "bluegrass": { genre: "Country/Americana", weight: 0.9 },
  "alt-country": { genre: "Country/Americana", weight: 0.9 },
  "country pop": { genre: "Country/Americana", weight: 0.9 },
  "country rock": { genre: "Country/Americana", weight: 0.85 },
  "outlaw country": { genre: "Country/Americana", weight: 0.95 },
  "nashville sound": { genre: "Country/Americana", weight: 0.95 },
  "new country": { genre: "Country/Americana", weight: 0.9 },
  "traditional country": { genre: "Country/Americana", weight: 0.95 },
  "texas country": { genre: "Country/Americana", weight: 0.95 },
  "honky tonk": { genre: "Country/Americana", weight: 0.95 },
  "western swing": { genre: "Country/Americana", weight: 0.9 },

  // ── Folk / Acoustic ───────────────────────────────────────────────────────
  "folk": { genre: "Folk/Acoustic", weight: 0.95 },
  "acoustic": { genre: "Folk/Acoustic", weight: 0.85 },
  "singer-songwriter": { genre: "Folk/Acoustic", weight: 0.9 },
  "folk pop": { genre: "Folk/Acoustic", weight: 0.85 },
  "contemporary folk": { genre: "Folk/Acoustic", weight: 0.95 },
  "traditional folk": { genre: "Folk/Acoustic", weight: 0.95 },
  "anti-folk": { genre: "Folk/Acoustic", weight: 0.9 },
  "celtic folk": { genre: "Folk/Acoustic", weight: 0.9 },
  "freak folk": { genre: "Folk/Acoustic", weight: 0.85 },
  "psychedelic folk": { genre: "Folk/Acoustic", weight: 0.85 },
  "neofolk": { genre: "Folk/Acoustic", weight: 0.9 },

  // ── Latin ─────────────────────────────────────────────────────────────────
  "latin": { genre: "Latin", weight: 0.9 },
  "reggaeton": { genre: "Latin", weight: 0.95 },
  "latin pop": { genre: "Latin", weight: 0.95 },
  "salsa": { genre: "Latin", weight: 0.95 },
  "bachata": { genre: "Latin", weight: 0.95 },
  "merengue": { genre: "Latin", weight: 0.95 },
  "cumbia": { genre: "Latin", weight: 0.95 },
  "bossa nova": { genre: "Latin", weight: 0.9 },
  "samba": { genre: "Latin", weight: 0.95 },
  "latin jazz": { genre: "Latin", weight: 0.85 },
  "mariachi": { genre: "Latin", weight: 0.95 },
  "flamenco": { genre: "Latin", weight: 0.9 },
  "urbano latino": { genre: "Latin", weight: 0.95 },
  "latin trap": { genre: "Latin", weight: 0.95 },
  "latin alternative": { genre: "Latin", weight: 0.9 },
  "dembow": { genre: "Latin", weight: 0.9 },

  // ── K-Pop ─────────────────────────────────────────────────────────────────
  "k-pop": { genre: "K-Pop", weight: 0.98 },
  "kpop": { genre: "K-Pop", weight: 0.98 },
  "korean pop": { genre: "K-Pop", weight: 0.98 },
  "korean r&b": { genre: "K-Pop", weight: 0.85 },
  "korean hip hop": { genre: "K-Pop", weight: 0.85 },
  "k-rap": { genre: "K-Pop", weight: 0.9 },
  "j-pop": { genre: "K-Pop", weight: 0.85 },
  "j-rock": { genre: "K-Pop", weight: 0.8 },
  "anime": { genre: "K-Pop", weight: 0.75 },
  "city pop": { genre: "K-Pop", weight: 0.7 },

  // ── Ambient / Lo-fi ───────────────────────────────────────────────────────
  "ambient": { genre: "Ambient/Lo-fi", weight: 0.95 },
  "lo-fi": { genre: "Ambient/Lo-fi", weight: 0.95 },
  "lofi": { genre: "Ambient/Lo-fi", weight: 0.95 },
  "downtempo": { genre: "Ambient/Lo-fi", weight: 0.9 },
  "chill": { genre: "Ambient/Lo-fi", weight: 0.8 },
  "chillhop": { genre: "Ambient/Lo-fi", weight: 0.9 },
  "study music": { genre: "Ambient/Lo-fi", weight: 0.9 },
  "new age": { genre: "Ambient/Lo-fi", weight: 0.85 },
  "drone": { genre: "Ambient/Lo-fi", weight: 0.85 },
  "dark ambient": { genre: "Ambient/Lo-fi", weight: 0.85 },
  "space music": { genre: "Ambient/Lo-fi", weight: 0.85 },

  // ── Soundtrack / Score ────────────────────────────────────────────────────
  "soundtrack": { genre: "Soundtrack/Score", weight: 0.95 },
  "score": { genre: "Soundtrack/Score", weight: 0.9 },
  "film score": { genre: "Soundtrack/Score", weight: 0.95 },
  "video game music": { genre: "Soundtrack/Score", weight: 0.95 },
  "game soundtrack": { genre: "Soundtrack/Score", weight: 0.95 },
  "musical": { genre: "Soundtrack/Score", weight: 0.9 },
  "show tunes": { genre: "Soundtrack/Score", weight: 0.95 },
  "tv soundtrack": { genre: "Soundtrack/Score", weight: 0.95 },

  // ── Reggae / Ska ──────────────────────────────────────────────────────────
  "reggae": { genre: "Reggae/Ska", weight: 0.95 },
  "ska": { genre: "Reggae/Ska", weight: 0.95 },
  "dancehall": { genre: "Reggae/Ska", weight: 0.9 },
  "dub": { genre: "Reggae/Ska", weight: 0.9 },
  "roots reggae": { genre: "Reggae/Ska", weight: 0.95 },
  "rocksteady": { genre: "Reggae/Ska", weight: 0.95 },
  "two-tone": { genre: "Reggae/Ska", weight: 0.9 },
  "ska punk": { genre: "Reggae/Ska", weight: 0.85 },

  // ── World / Regional ──────────────────────────────────────────────────────
  "world music": { genre: "World/Regional", weight: 0.9 },
  "afrobeat": { genre: "World/Regional", weight: 0.9 },
  "afrobeats": { genre: "World/Regional", weight: 0.85 },
  "highlife": { genre: "World/Regional", weight: 0.95 },
  "amapiano": { genre: "World/Regional", weight: 0.95 },
  "juju": { genre: "World/Regional", weight: 0.95 },
  "bollywood": { genre: "World/Regional", weight: 0.95 },
  "indian classical": { genre: "World/Regional", weight: 0.95 },
  "bhangra": { genre: "World/Regional", weight: 0.95 },
  "arabic pop": { genre: "World/Regional", weight: 0.95 },
  "turkish pop": { genre: "World/Regional", weight: 0.9 },
  "celtic": { genre: "World/Regional", weight: 0.85 },
  "fado": { genre: "World/Regional", weight: 0.95 },
  "zouk": { genre: "World/Regional", weight: 0.95 },
  "mbalax": { genre: "World/Regional", weight: 0.95 },
  "buena vista social club": { genre: "World/Regional", weight: 0.9 },
};

/**
 * Look up a normalized genre string in the canonical map.
 * Returns undefined if no match found.
 */
export function lookupCanonical(normalized: string): CanonicalEntry | undefined {
  return CANONICAL_MAP[normalized];
}
